apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8-deployment-demo
  labels:
    app: helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
        - name: helloworld
          image: nginx:1.14.2
          ports:
            - containerPort: 8080