apiVersion: apps/v1
kind: Deployment
metadata:
  name: students
  labels:
    app: students
spec:
  replicas: 1
  selector:
    matchLabels:
      app: students
  template:
    metadata:
      labels:
        app: students
    spec:
      containers:
        - name: students
          image: students
          imagePullPolicy: Never
          ports:
            - containerPort: 8080