# permissions for end users to view myprojects.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: myproject-viewer-role
rules:
- apiGroups:
  - myproject.io
  resources:
  - myprojects
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - myproject.io
  resources:
  - myprojects/status
  verbs:
  - get
