apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    move2kube.konveyor.io/service.expose: "true"
  creationTimestamp: null
  labels:
    move2kube.konveyor.io/service: spring-music
  name: spring-music
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
        - env:
            - name: JBP_CONFIG_SPRING_AUTO_RECONFIGURATION
              value: '{enabled: false}'
            - name: SPRING_PROFILES_ACTIVE
              value: http2
            - name: PORT
              value: "8080"
          image: index.docker.io/myproject/spring-music:latest
          imagePullPolicy: Always
          name: spring-music
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
