apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    move2kube.konveyor.io/service.expose: "true"
  creationTimestamp: null
  labels:
    move2kube.konveyor.io/service: student
  name: student
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
        - env:
            - name: PORT
              value: "8080"
          image: index.docker.io/myproject/student:latest
          imagePullPolicy: Always
          name: student
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
